### ISSUE TITLE
Quick Start Guide issues

### ISSUE THREAD

**Issue by oj-amazing** [antmicro/cocotb-verilator-build#2]
Hitting some bumps when setting up my environment.

1. `env/bin/verilator` does not exist. Is this expected? I had to install Verilator using `sudo apt-get install verilator` instead.

2. `make env/bin/cocotb-config` run to completion, but running `./cocotb-config` results in an error message: `cocotb-config: command not found`. Even doing `pip install cocotb` results in the same issue. Am I missing a package or dependency?

**Comment by ZvonimirBandic** [comment]
Can you move the discussion to
https://github.com/chipsalliance/tools-cocotb-verilator-build?
THANKS!
Zvonimir

**Comment by oj-amazing** [comment]
Done!
